### ISSUE TITLE
SRET/MRET questions about Svvptc

### ISSUE THREAD

**Issue by terranfund** [riscv/riscv-svvptc#13]
1. Does MRET also guarantee the page visibility with a Valid bit of PTEs from 0 to 1 like statement SRET in
https://github.com/riscv/riscv-svvptc/blob/main/svvptc.adoc?
2. If question 1 is true, does it mean SRET/MRET has the overhead of guaranteeing previous stores for Valid bit, from 0 to 1, visible to the current hart are ordered before subsequent instructions executed by the same hart, like SFENCE.W.INVAL?

**Comment by ved-rivos** [comment]
> Does MRET also guarantee the page visible with Valid bit of PTEs from 0 to 1 like statement SRET in

When the Svvptc extension is implemented, explicit stores that update the Valid bit of leaf and/or non-leaf PTEs from 0 to 1 and are visible to a hart will eventually become visible within a bounded timeframe to subsequent implicit accesses by that hart to such PTEs. As specified, neither SRET nor MRET have any part to play in making such PTE writes visible.

**Comment by terranfund** [comment]
thanks Ved.
Third question:
Does invalid page include the page whose pte.A is zero?

**Comment by ved-rivos** [comment]
This extension only applies to the PTE updates to change the Valid bit of leaf and/or non-leaf PTEs from 0 to 1.

**Comment by terranfund** [comment]
Thanks again, Ved.
I would like to know if the ptes read for VS-level page tables, subject to G-stage address translation, are applied as well.
Will explicit stores that update the Valid bit of lead and/or non-leaf of such immediate PTEs from 0 to 1 and are visible to a hart eventually become visible within a bounded timeframe to subsequent implicit accesses by that hart to such PTEs?

**Comment by ved-rivos** [comment]
The update to make a PTE valid will be visible within a bounded timeframe to subsequent implicit accesses even when the address of the PTE to update was determine by the store using two-stage address translation or when the address of the implicit access to the PTE was determined using two-stage address translation.

**Comment by terranfund** [comment]
Pardon,
Allow me to question again,
I would like to know if the ptes read along with implicit memory access, subject to G-stage address translation, for VS-stage address translation are applied as well, not the VS-level page table entries.
Will the update to make such immediate PTEs valid be visible within a bounded timeframe to subsequent implicit accesses?

**Comment by ved-rivos** [comment]
This extension is applicable for leaf and non-leaf G-stage PTEs  as well as leaf and non-leaf VS-stage PTEs.

**Comment by terranfund** [comment]
Hi Ved,
What I meant is when a guest-page fault, caused by pte valid bit equal to 0, due to an implicit memory access for/during VS-stage address translation, will the fix to update the valid bit to 1 be visible within a bounded timeframe to subsequent implicit accesses?

**Comment by ved-rivos** [comment]
did the "is applicable to leaf and non-leaf G-stage PTEs" not cover this case? The G-stage PTEs may be providing translation for a VS-stage leaf PTE, VS-stage non-leaf PTE, or a final GPA determined through VS-stage address translation. The Svvptc extension is applicable to making a leaf or non-leaf PTE Valid - for all PTEs in all kinds page tables provided by the virtual memory system.

**Comment by terranfund** [comment]
Got it. Ved.
Thank you.
