### ISSUE TITLE
Several Questions about the Store

### ISSUE THREAD

**Issue by haosun86** [riscv/riscv-svvptc#15]
Hi,

The specification has the following description:
"When the Svvptc extension is implemented, explicit stores that update the Valid bit of leaf and/or non-leaf PTEs from 0 to 1 and are visible to a hart will eventually become visible within a bounded timeframe to subsequent implicit accesses by that hart to such PTEs."

I have several questions:
(1) How to determine the bounded time value?
(2) Do we need to distinguish PTE store, and non-PTE store? If not, all stores are immediately observable which may have side effect on performance, power, etc

Thanks
Hao Sun

**Comment by ved-rivos** [comment]
> (1) How to determine the bounded time value?

The bounded time value is implementation defined. However, the implementation that claims support for Svvptc has a bounded time frame for visibility of PTE stores such that a need for memory-management fence is not required with the key being that it should be beneficial from a performance perspective to guide the software to not issue the memory management fence. On implementations that do not claim support for Svvptc, such as those that cache invalid PTEs, software will issue the memory management fence.

> Do we need to distinguish PTE store, and non-PTE store? If not, all stores are immediately observable which may have side effect on performance, power, etc

An implementation that claims Svvptc makes a statement bout PTE updating stores. For instance,  it does not cache invalid PTEs such that the PTE updating stores will be visible eventually within a bounded time frame to implicit accesses. Usually this does not require implementations to differentiate between stores. Svvptc does not require "immediate observability" - it states - "eventually become visible within a bounded timeframe".
