### ISSUE TITLE
Multiple Harts

### ISSUE THREAD

**Issue by zhonghochen** [riscv/riscv-svvptc#20]
When Svvptc is implemented, do explicit stores by a hart (hart A) that update the Valid bit of leaf and/or non-leaf PTEs from 0 to 1 become visible to another hart (hart B)?

Svvptc relieves an operating system from executing certain memory-management instructions, such as SFENCE.VMA or SINVAL.VMA.
Howerver, it's not clear whether other charts should be notified when updating the Valid bit from 0 to 1.

Quote Volume II: RISC-V Privileged Architectures V20211203
> SFENCE.VMA orders only the local hart implicit references to the memory-management data structures.
> Other harts must be notified separately when the memory-management data structures have been modified.

**Comment by ved-rivos** [comment]
hope that answered the question.
